name: yt_dupe
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  get_it: ^7.6.4
  hive_flutter: ^1.1.0
  injectable: ^1.5.3

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
